# Generated by Django 4.2.1 on 2023-06-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicmaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='job.candidatemaster'),
        ),
        migrations.AlterField(
            model_name='experiencemaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='job.candidatemaster'),
        ),
        migrations.AlterField(
            model_name='languageknownmaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='job.candidatemaster'),
        ),
        migrations.AlterField(
            model_name='preferencemaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='job.candidatemaster'),
        ),
        migrations.AlterField(
            model_name='referencemaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='job.candidatemaster'),
        ),
        migrations.AlterField(
            model_name='technologyknownmaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='job.candidatemaster'),
        ),
    ]
